### ISSUE TITLE
Publikacja w sklepie Android

### ISSUE THREAD

**Issue by owlcode** [wutee/propsy-mobile-deliveryman#1]

**Comment by owlcode** [comment]
@wutee/wutee kto chętny? 

Obydwie aplikacje do sklepu Android + zwięzła instrukcja jak to robić? 🎖 

Cenne doświadczenie z pewnością 💥 ⬆️

**Comment by churskir** [comment]
Dalej robimy to w parach? Jeśli tak, to razem z @achellko zgłaszamy się ;)
